export const ADMIN_RECENT_ACTIVITIES_DEFAULT_PAGE = 1;
export const ADMIN_RECENT_ACTIVITIES_DEFAULT_LIMIT = 15;
export const ADMIN_RECENT_ACTIVITIES_MAX_LIMIT = 100;
export const ADMIN_RECENT_ACTIVITIES_DEFAULT_SORT_ORDER = 'desc' as const;
